namespace GESTION_DE_PROJET.Views.Manage_Users
{
    partial class frmAddEditUser
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if ( disposing && (components != null) )
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmAddEditUser));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textMatrcile = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNom = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textPrenom = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.RoleEmploye = new Bunifu.UI.WinForms.BunifuDropdown();
            this.textAdress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textTelephone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.NomLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtNomContact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 64.25F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel2, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(804, 410);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 165F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.Controls.Add(this.bunifuLabel3, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.bunifuLabel1, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.bunifuLabel2, 0, 2);
            this.tableLayoutPanel2.Controls.Add(this.bunifuLabel4, 0, 3);
            this.tableLayoutPanel2.Controls.Add(this.bunifuLabel5, 0, 4);
            this.tableLayoutPanel2.Controls.Add(this.bunifuLabel6, 0, 6);
            this.tableLayoutPanel2.Controls.Add(this.bunifuLabel7, 0, 7);
            this.tableLayoutPanel2.Controls.Add(this.textMatrcile, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.txtNom, 1, 1);
            this.tableLayoutPanel2.Controls.Add(this.textPrenom, 1, 2);
            this.tableLayoutPanel2.Controls.Add(this.textEmail, 1, 6);
            this.tableLayoutPanel2.Controls.Add(this.bunifuLabel8, 0, 8);
            this.tableLayoutPanel2.Controls.Add(this.RoleEmploye, 1, 8);
            this.tableLayoutPanel2.Controls.Add(this.textAdress, 1, 3);
            this.tableLayoutPanel2.Controls.Add(this.textTelephone, 1, 4);
            this.tableLayoutPanel2.Controls.Add(this.textPassword, 1, 7);
            this.tableLayoutPanel2.Controls.Add(this.tableLayoutPanel3, 0, 9);
            this.tableLayoutPanel2.Controls.Add(this.NomLabel, 0, 5);
            this.tableLayoutPanel2.Controls.Add(this.txtNomContact, 1, 5);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 10;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 48F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(798, 404);
            this.tableLayoutPanel2.TabIndex = 0;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(3, 11);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(54, 17);
            this.bunifuLabel3.TabIndex = 1;
            this.bunifuLabel3.Text = "Matricule";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(3, 50);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(29, 17);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Nom ";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(3, 89);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(45, 17);
            this.bunifuLabel2.TabIndex = 1;
            this.bunifuLabel2.Text = "Prenom";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(3, 128);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(40, 17);
            this.bunifuLabel4.TabIndex = 1;
            this.bunifuLabel4.Text = "Adress";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(3, 167);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(61, 17);
            this.bunifuLabel5.TabIndex = 1;
            this.bunifuLabel5.Text = "Telephone";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel6.Location = new System.Drawing.Point(3, 245);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(31, 17);
            this.bunifuLabel6.TabIndex = 1;
            this.bunifuLabel6.Text = "Email";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel7.Location = new System.Drawing.Point(3, 284);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(81, 17);
            this.bunifuLabel7.TabIndex = 1;
            this.bunifuLabel7.Text = "Mot de passe";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textMatrcile
            // 
            this.textMatrcile.AcceptsReturn = false;
            this.textMatrcile.AcceptsTab = false;
            this.textMatrcile.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.textMatrcile.AnimationSpeed = 200;
            this.textMatrcile.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textMatrcile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textMatrcile.BackColor = System.Drawing.Color.Transparent;
            this.textMatrcile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textMatrcile.BackgroundImage")));
            this.textMatrcile.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textMatrcile.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textMatrcile.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textMatrcile.BorderColorIdle = System.Drawing.Color.Silver;
            this.textMatrcile.BorderRadius = 15;
            this.textMatrcile.BorderThickness = 1;
            this.textMatrcile.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textMatrcile.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textMatrcile.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textMatrcile.DefaultText = "";
            this.textMatrcile.Enabled = false;
            this.textMatrcile.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            this.textMatrcile.ForeColor = System.Drawing.Color.White;
            this.textMatrcile.HideSelection = true;
            this.textMatrcile.IconLeft = null;
            this.textMatrcile.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textMatrcile.IconPadding = 10;
            this.textMatrcile.IconRight = null;
            this.textMatrcile.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textMatrcile.Lines = new string[0];
            this.textMatrcile.Location = new System.Drawing.Point(168, 3);
            this.textMatrcile.MaxLength = 32767;
            this.textMatrcile.MinimumSize = new System.Drawing.Size(1, 1);
            this.textMatrcile.Modified = false;
            this.textMatrcile.Multiline = false;
            this.textMatrcile.Name = "textMatrcile";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textMatrcile.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textMatrcile.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textMatrcile.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            stateProperties36.ForeColor = System.Drawing.Color.White;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textMatrcile.OnIdleState = stateProperties36;
            this.textMatrcile.Padding = new System.Windows.Forms.Padding(3);
            this.textMatrcile.PasswordChar = '\0';
            this.textMatrcile.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textMatrcile.PlaceholderText = "entrer matricule";
            this.textMatrcile.ReadOnly = false;
            this.textMatrcile.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textMatrcile.SelectedText = "";
            this.textMatrcile.SelectionLength = 0;
            this.textMatrcile.SelectionStart = 0;
            this.textMatrcile.ShortcutsEnabled = true;
            this.textMatrcile.Size = new System.Drawing.Size(627, 33);
            this.textMatrcile.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textMatrcile.TabIndex = 7;
            this.textMatrcile.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textMatrcile.TextMarginBottom = 0;
            this.textMatrcile.TextMarginLeft = 3;
            this.textMatrcile.TextMarginTop = 0;
            this.textMatrcile.TextPlaceholder = "entrer matricule";
            this.textMatrcile.UseSystemPasswordChar = false;
            this.textMatrcile.WordWrap = true;
            // 
            // txtNom
            // 
            this.txtNom.AcceptsReturn = false;
            this.txtNom.AcceptsTab = false;
            this.txtNom.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtNom.AnimationSpeed = 200;
            this.txtNom.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNom.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNom.BackColor = System.Drawing.Color.Transparent;
            this.txtNom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNom.BackgroundImage")));
            this.txtNom.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNom.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNom.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNom.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNom.BorderRadius = 15;
            this.txtNom.BorderThickness = 1;
            this.txtNom.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNom.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNom.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNom.DefaultText = "";
            this.txtNom.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            this.txtNom.ForeColor = System.Drawing.Color.White;
            this.txtNom.HideSelection = true;
            this.txtNom.IconLeft = null;
            this.txtNom.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNom.IconPadding = 10;
            this.txtNom.IconRight = null;
            this.txtNom.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNom.Lines = new string[0];
            this.txtNom.Location = new System.Drawing.Point(168, 42);
            this.txtNom.MaxLength = 32767;
            this.txtNom.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNom.Modified = false;
            this.txtNom.Multiline = false;
            this.txtNom.Name = "txtNom";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNom.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNom.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNom.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            stateProperties40.ForeColor = System.Drawing.Color.White;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNom.OnIdleState = stateProperties40;
            this.txtNom.Padding = new System.Windows.Forms.Padding(3);
            this.txtNom.PasswordChar = '\0';
            this.txtNom.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNom.PlaceholderText = "Enter text";
            this.txtNom.ReadOnly = false;
            this.txtNom.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNom.SelectedText = "";
            this.txtNom.SelectionLength = 0;
            this.txtNom.SelectionStart = 0;
            this.txtNom.ShortcutsEnabled = true;
            this.txtNom.Size = new System.Drawing.Size(627, 33);
            this.txtNom.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNom.TabIndex = 7;
            this.txtNom.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNom.TextMarginBottom = 0;
            this.txtNom.TextMarginLeft = 3;
            this.txtNom.TextMarginTop = 0;
            this.txtNom.TextPlaceholder = "Enter text";
            this.txtNom.UseSystemPasswordChar = false;
            this.txtNom.WordWrap = true;
            // 
            // textPrenom
            // 
            this.textPrenom.AcceptsReturn = false;
            this.textPrenom.AcceptsTab = false;
            this.textPrenom.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.textPrenom.AnimationSpeed = 200;
            this.textPrenom.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textPrenom.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textPrenom.BackColor = System.Drawing.Color.Transparent;
            this.textPrenom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textPrenom.BackgroundImage")));
            this.textPrenom.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textPrenom.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textPrenom.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textPrenom.BorderColorIdle = System.Drawing.Color.Silver;
            this.textPrenom.BorderRadius = 15;
            this.textPrenom.BorderThickness = 1;
            this.textPrenom.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textPrenom.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textPrenom.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textPrenom.DefaultText = "";
            this.textPrenom.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            this.textPrenom.ForeColor = System.Drawing.Color.White;
            this.textPrenom.HideSelection = true;
            this.textPrenom.IconLeft = null;
            this.textPrenom.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textPrenom.IconPadding = 10;
            this.textPrenom.IconRight = null;
            this.textPrenom.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textPrenom.Lines = new string[0];
            this.textPrenom.Location = new System.Drawing.Point(168, 81);
            this.textPrenom.MaxLength = 32767;
            this.textPrenom.MinimumSize = new System.Drawing.Size(1, 1);
            this.textPrenom.Modified = false;
            this.textPrenom.Multiline = false;
            this.textPrenom.Name = "textPrenom";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textPrenom.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textPrenom.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textPrenom.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            stateProperties44.ForeColor = System.Drawing.Color.White;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textPrenom.OnIdleState = stateProperties44;
            this.textPrenom.Padding = new System.Windows.Forms.Padding(3);
            this.textPrenom.PasswordChar = '\0';
            this.textPrenom.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textPrenom.PlaceholderText = "Enter text";
            this.textPrenom.ReadOnly = false;
            this.textPrenom.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textPrenom.SelectedText = "";
            this.textPrenom.SelectionLength = 0;
            this.textPrenom.SelectionStart = 0;
            this.textPrenom.ShortcutsEnabled = true;
            this.textPrenom.Size = new System.Drawing.Size(627, 33);
            this.textPrenom.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textPrenom.TabIndex = 7;
            this.textPrenom.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textPrenom.TextMarginBottom = 0;
            this.textPrenom.TextMarginLeft = 3;
            this.textPrenom.TextMarginTop = 0;
            this.textPrenom.TextPlaceholder = "Enter text";
            this.textPrenom.UseSystemPasswordChar = false;
            this.textPrenom.WordWrap = true;
            // 
            // textEmail
            // 
            this.textEmail.AcceptsReturn = false;
            this.textEmail.AcceptsTab = false;
            this.textEmail.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.textEmail.AnimationSpeed = 200;
            this.textEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textEmail.BackColor = System.Drawing.Color.Transparent;
            this.textEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textEmail.BackgroundImage")));
            this.textEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.textEmail.BorderRadius = 15;
            this.textEmail.BorderThickness = 1;
            this.textEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textEmail.DefaultText = "";
            this.textEmail.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            this.textEmail.ForeColor = System.Drawing.Color.White;
            this.textEmail.HideSelection = true;
            this.textEmail.IconLeft = null;
            this.textEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textEmail.IconPadding = 10;
            this.textEmail.IconRight = null;
            this.textEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textEmail.Lines = new string[0];
            this.textEmail.Location = new System.Drawing.Point(168, 237);
            this.textEmail.MaxLength = 32767;
            this.textEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.textEmail.Modified = false;
            this.textEmail.Multiline = false;
            this.textEmail.Name = "textEmail";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textEmail.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textEmail.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textEmail.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            stateProperties48.ForeColor = System.Drawing.Color.White;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textEmail.OnIdleState = stateProperties48;
            this.textEmail.Padding = new System.Windows.Forms.Padding(3);
            this.textEmail.PasswordChar = '\0';
            this.textEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textEmail.PlaceholderText = "Enter text";
            this.textEmail.ReadOnly = false;
            this.textEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textEmail.SelectedText = "";
            this.textEmail.SelectionLength = 0;
            this.textEmail.SelectionStart = 0;
            this.textEmail.ShortcutsEnabled = true;
            this.textEmail.Size = new System.Drawing.Size(627, 33);
            this.textEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textEmail.TabIndex = 7;
            this.textEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textEmail.TextMarginBottom = 0;
            this.textEmail.TextMarginLeft = 3;
            this.textEmail.TextMarginTop = 0;
            this.textEmail.TextPlaceholder = "Enter text";
            this.textEmail.UseSystemPasswordChar = false;
            this.textEmail.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel8.Location = new System.Drawing.Point(3, 323);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(80, 17);
            this.bunifuLabel8.TabIndex = 1;
            this.bunifuLabel8.Text = "Role Employe";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // RoleEmploye
            // 
            this.RoleEmploye.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.RoleEmploye.BackColor = System.Drawing.Color.Transparent;
            this.RoleEmploye.BackgroundColor = System.Drawing.Color.Transparent;
            this.RoleEmploye.BorderColor = System.Drawing.Color.Silver;
            this.RoleEmploye.BorderRadius = 1;
            this.RoleEmploye.Color = System.Drawing.Color.Silver;
            this.RoleEmploye.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.RoleEmploye.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.RoleEmploye.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RoleEmploye.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.RoleEmploye.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.RoleEmploye.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.RoleEmploye.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.RoleEmploye.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.RoleEmploye.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.RoleEmploye.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.RoleEmploye.FillDropDown = true;
            this.RoleEmploye.FillIndicator = false;
            this.RoleEmploye.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.RoleEmploye.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.RoleEmploye.ForeColor = System.Drawing.Color.White;
            this.RoleEmploye.FormattingEnabled = true;
            this.RoleEmploye.Icon = null;
            this.RoleEmploye.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.RoleEmploye.IndicatorColor = System.Drawing.Color.Gray;
            this.RoleEmploye.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.RoleEmploye.ItemBackColor = System.Drawing.Color.White;
            this.RoleEmploye.ItemBorderColor = System.Drawing.Color.White;
            this.RoleEmploye.ItemForeColor = System.Drawing.Color.Black;
            this.RoleEmploye.ItemHeight = 26;
            this.RoleEmploye.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.RoleEmploye.ItemHighLightForeColor = System.Drawing.Color.White;
            this.RoleEmploye.ItemTopMargin = 3;
            this.RoleEmploye.Location = new System.Drawing.Point(168, 315);
            this.RoleEmploye.Name = "RoleEmploye";
            this.RoleEmploye.Size = new System.Drawing.Size(627, 32);
            this.RoleEmploye.TabIndex = 9;
            this.RoleEmploye.Text = null;
            this.RoleEmploye.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.RoleEmploye.TextLeftMargin = 5;
            // 
            // textAdress
            // 
            this.textAdress.AcceptsReturn = false;
            this.textAdress.AcceptsTab = false;
            this.textAdress.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.textAdress.AnimationSpeed = 200;
            this.textAdress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textAdress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textAdress.BackColor = System.Drawing.Color.Transparent;
            this.textAdress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textAdress.BackgroundImage")));
            this.textAdress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textAdress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textAdress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textAdress.BorderColorIdle = System.Drawing.Color.Silver;
            this.textAdress.BorderRadius = 15;
            this.textAdress.BorderThickness = 1;
            this.textAdress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textAdress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textAdress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textAdress.DefaultText = "";
            this.textAdress.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            this.textAdress.ForeColor = System.Drawing.Color.White;
            this.textAdress.HideSelection = true;
            this.textAdress.IconLeft = null;
            this.textAdress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textAdress.IconPadding = 10;
            this.textAdress.IconRight = null;
            this.textAdress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textAdress.Lines = new string[0];
            this.textAdress.Location = new System.Drawing.Point(168, 120);
            this.textAdress.MaxLength = 32767;
            this.textAdress.MinimumSize = new System.Drawing.Size(1, 1);
            this.textAdress.Modified = false;
            this.textAdress.Multiline = false;
            this.textAdress.Name = "textAdress";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textAdress.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textAdress.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textAdress.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            stateProperties52.ForeColor = System.Drawing.Color.White;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textAdress.OnIdleState = stateProperties52;
            this.textAdress.Padding = new System.Windows.Forms.Padding(3);
            this.textAdress.PasswordChar = '\0';
            this.textAdress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textAdress.PlaceholderText = "Enter text";
            this.textAdress.ReadOnly = false;
            this.textAdress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textAdress.SelectedText = "";
            this.textAdress.SelectionLength = 0;
            this.textAdress.SelectionStart = 0;
            this.textAdress.ShortcutsEnabled = true;
            this.textAdress.Size = new System.Drawing.Size(627, 33);
            this.textAdress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textAdress.TabIndex = 11;
            this.textAdress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textAdress.TextMarginBottom = 0;
            this.textAdress.TextMarginLeft = 3;
            this.textAdress.TextMarginTop = 0;
            this.textAdress.TextPlaceholder = "Enter text";
            this.textAdress.UseSystemPasswordChar = false;
            this.textAdress.WordWrap = true;
            // 
            // textTelephone
            // 
            this.textTelephone.AcceptsReturn = false;
            this.textTelephone.AcceptsTab = false;
            this.textTelephone.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.textTelephone.AnimationSpeed = 200;
            this.textTelephone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textTelephone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textTelephone.BackColor = System.Drawing.Color.Transparent;
            this.textTelephone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textTelephone.BackgroundImage")));
            this.textTelephone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textTelephone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textTelephone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textTelephone.BorderColorIdle = System.Drawing.Color.Silver;
            this.textTelephone.BorderRadius = 15;
            this.textTelephone.BorderThickness = 1;
            this.textTelephone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textTelephone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textTelephone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textTelephone.DefaultText = "";
            this.textTelephone.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            this.textTelephone.ForeColor = System.Drawing.Color.White;
            this.textTelephone.HideSelection = true;
            this.textTelephone.IconLeft = null;
            this.textTelephone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textTelephone.IconPadding = 10;
            this.textTelephone.IconRight = null;
            this.textTelephone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textTelephone.Lines = new string[0];
            this.textTelephone.Location = new System.Drawing.Point(168, 159);
            this.textTelephone.MaxLength = 32767;
            this.textTelephone.MinimumSize = new System.Drawing.Size(1, 1);
            this.textTelephone.Modified = false;
            this.textTelephone.Multiline = false;
            this.textTelephone.Name = "textTelephone";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textTelephone.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textTelephone.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textTelephone.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            stateProperties56.ForeColor = System.Drawing.Color.White;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textTelephone.OnIdleState = stateProperties56;
            this.textTelephone.Padding = new System.Windows.Forms.Padding(3);
            this.textTelephone.PasswordChar = '\0';
            this.textTelephone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textTelephone.PlaceholderText = "Enter text";
            this.textTelephone.ReadOnly = false;
            this.textTelephone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textTelephone.SelectedText = "";
            this.textTelephone.SelectionLength = 0;
            this.textTelephone.SelectionStart = 0;
            this.textTelephone.ShortcutsEnabled = true;
            this.textTelephone.Size = new System.Drawing.Size(627, 33);
            this.textTelephone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textTelephone.TabIndex = 12;
            this.textTelephone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textTelephone.TextMarginBottom = 0;
            this.textTelephone.TextMarginLeft = 3;
            this.textTelephone.TextMarginTop = 0;
            this.textTelephone.TextPlaceholder = "Enter text";
            this.textTelephone.UseSystemPasswordChar = false;
            this.textTelephone.WordWrap = true;
            // 
            // textPassword
            // 
            this.textPassword.AcceptsReturn = false;
            this.textPassword.AcceptsTab = false;
            this.textPassword.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.textPassword.AnimationSpeed = 200;
            this.textPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textPassword.BackColor = System.Drawing.Color.Transparent;
            this.textPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textPassword.BackgroundImage")));
            this.textPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.textPassword.BorderRadius = 15;
            this.textPassword.BorderThickness = 1;
            this.textPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textPassword.DefaultText = "";
            this.textPassword.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            this.textPassword.ForeColor = System.Drawing.Color.White;
            this.textPassword.HideSelection = true;
            this.textPassword.IconLeft = null;
            this.textPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textPassword.IconPadding = 10;
            this.textPassword.IconRight = null;
            this.textPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textPassword.Lines = new string[0];
            this.textPassword.Location = new System.Drawing.Point(168, 276);
            this.textPassword.MaxLength = 32767;
            this.textPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.textPassword.Modified = false;
            this.textPassword.Multiline = false;
            this.textPassword.Name = "textPassword";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textPassword.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textPassword.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textPassword.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            stateProperties60.ForeColor = System.Drawing.Color.White;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textPassword.OnIdleState = stateProperties60;
            this.textPassword.Padding = new System.Windows.Forms.Padding(3);
            this.textPassword.PasswordChar = '\0';
            this.textPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textPassword.PlaceholderText = "Enter text";
            this.textPassword.ReadOnly = false;
            this.textPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textPassword.SelectedText = "";
            this.textPassword.SelectionLength = 0;
            this.textPassword.SelectionStart = 0;
            this.textPassword.ShortcutsEnabled = true;
            this.textPassword.Size = new System.Drawing.Size(627, 33);
            this.textPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textPassword.TabIndex = 10;
            this.textPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textPassword.TextMarginBottom = 0;
            this.textPassword.TextMarginLeft = 3;
            this.textPassword.TextMarginTop = 0;
            this.textPassword.TextPlaceholder = "Enter text";
            this.textPassword.UseSystemPasswordChar = false;
            this.textPassword.WordWrap = true;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 4;
            this.tableLayoutPanel2.SetColumnSpan(this.tableLayoutPanel3, 2);
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Controls.Add(this.btnCancel, 2, 0);
            this.tableLayoutPanel3.Controls.Add(this.btnSave, 1, 0);
            this.tableLayoutPanel3.Controls.Add(this.btnClose, 3, 0);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(3, 354);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 1;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(792, 47);
            this.tableLayoutPanel3.TabIndex = 13;
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.Red;
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Annuler";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges4;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.Red;
            this.btnCancel.IdleBorderRadius = 1;
            this.btnCancel.IdleBorderThickness = 1;
            this.btnCancel.IdleFillColor = System.Drawing.Color.Red;
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(399, 3);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 1;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCancel.onHoverState.BorderRadius = 1;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.btnCancel.OnIdleState.BorderRadius = 1;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancel.OnPressedState.BorderRadius = 1;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(125, 35);
            this.btnCancel.TabIndex = 2;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "Sauvegarder";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges5;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btnSave.IdleBorderRadius = 1;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(268, 3);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 1;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 1;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btnSave.OnIdleState.BorderRadius = 1;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 1;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(125, 35);
            this.btnSave.TabIndex = 2;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // NomLabel
            // 
            this.NomLabel.AllowParentOverrides = false;
            this.NomLabel.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.NomLabel.AutoEllipsis = false;
            this.NomLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.NomLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.NomLabel.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NomLabel.ForeColor = System.Drawing.Color.White;
            this.NomLabel.Location = new System.Drawing.Point(3, 206);
            this.NomLabel.Name = "NomLabel";
            this.NomLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.NomLabel.Size = new System.Drawing.Size(77, 17);
            this.NomLabel.TabIndex = 1;
            this.NomLabel.Text = "Nom Contact";
            this.NomLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.NomLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtNomContact
            // 
            this.txtNomContact.AcceptsReturn = false;
            this.txtNomContact.AcceptsTab = false;
            this.txtNomContact.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtNomContact.AnimationSpeed = 200;
            this.txtNomContact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNomContact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNomContact.BackColor = System.Drawing.Color.Transparent;
            this.txtNomContact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNomContact.BackgroundImage")));
            this.txtNomContact.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNomContact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNomContact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNomContact.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNomContact.BorderRadius = 15;
            this.txtNomContact.BorderThickness = 1;
            this.txtNomContact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNomContact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNomContact.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNomContact.DefaultText = "";
            this.txtNomContact.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            this.txtNomContact.ForeColor = System.Drawing.Color.White;
            this.txtNomContact.HideSelection = true;
            this.txtNomContact.IconLeft = null;
            this.txtNomContact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNomContact.IconPadding = 10;
            this.txtNomContact.IconRight = null;
            this.txtNomContact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNomContact.Lines = new string[0];
            this.txtNomContact.Location = new System.Drawing.Point(168, 198);
            this.txtNomContact.MaxLength = 32767;
            this.txtNomContact.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNomContact.Modified = false;
            this.txtNomContact.Multiline = false;
            this.txtNomContact.Name = "txtNomContact";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNomContact.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNomContact.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNomContact.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            stateProperties64.ForeColor = System.Drawing.Color.White;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNomContact.OnIdleState = stateProperties64;
            this.txtNomContact.Padding = new System.Windows.Forms.Padding(3);
            this.txtNomContact.PasswordChar = '\0';
            this.txtNomContact.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNomContact.PlaceholderText = "Enter text";
            this.txtNomContact.ReadOnly = false;
            this.txtNomContact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNomContact.SelectedText = "";
            this.txtNomContact.SelectionLength = 0;
            this.txtNomContact.SelectionStart = 0;
            this.txtNomContact.ShortcutsEnabled = true;
            this.txtNomContact.Size = new System.Drawing.Size(627, 33);
            this.txtNomContact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNomContact.TabIndex = 7;
            this.txtNomContact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNomContact.TextMarginBottom = 0;
            this.txtNomContact.TextMarginLeft = 3;
            this.txtNomContact.TextMarginTop = 0;
            this.txtNomContact.TextPlaceholder = "Enter text";
            this.txtNomContact.UseSystemPasswordChar = false;
            this.txtNomContact.WordWrap = true;
            // 
            // btnClose
            // 
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowMouseEffects = true;
            this.btnClose.AllowToggling = false;
            this.btnClose.AnimationSpeed = 200;
            this.btnClose.AutoGenerateColors = false;
            this.btnClose.AutoRoundBorders = false;
            this.btnClose.AutoSizeLeftIcon = true;
            this.btnClose.AutoSizeRightIcon = true;
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btnClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose.BackgroundImage")));
            this.btnClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.ButtonText = "Fermer";
            this.btnClose.ButtonTextMarginLeft = 0;
            this.btnClose.ColorContrastOnClick = 45;
            this.btnClose.ColorContrastOnHover = 45;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnClose.CustomizableEdges = borderEdges6;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnClose.ForeColor = System.Drawing.Color.White;
            this.btnClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose.IconMarginLeft = 11;
            this.btnClose.IconPadding = 10;
            this.btnClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose.IconSize = 25;
            this.btnClose.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btnClose.IdleBorderRadius = 1;
            this.btnClose.IdleBorderThickness = 1;
            this.btnClose.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btnClose.IdleIconLeftImage = null;
            this.btnClose.IdleIconRightImage = null;
            this.btnClose.IndicateFocus = false;
            this.btnClose.Location = new System.Drawing.Point(530, 3);
            this.btnClose.Name = "btnClose";
            this.btnClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.OnDisabledState.BorderRadius = 1;
            this.btnClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnDisabledState.BorderThickness = 1;
            this.btnClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.OnDisabledState.IconLeftImage = null;
            this.btnClose.OnDisabledState.IconRightImage = null;
            this.btnClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClose.onHoverState.BorderRadius = 1;
            this.btnClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.onHoverState.BorderThickness = 1;
            this.btnClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClose.onHoverState.IconLeftImage = null;
            this.btnClose.onHoverState.IconRightImage = null;
            this.btnClose.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btnClose.OnIdleState.BorderRadius = 1;
            this.btnClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnIdleState.BorderThickness = 1;
            this.btnClose.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btnClose.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnIdleState.IconLeftImage = null;
            this.btnClose.OnIdleState.IconRightImage = null;
            this.btnClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose.OnPressedState.BorderRadius = 1;
            this.btnClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnPressedState.BorderThickness = 1;
            this.btnClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnPressedState.IconLeftImage = null;
            this.btnClose.OnPressedState.IconRightImage = null;
            this.btnClose.Size = new System.Drawing.Size(125, 35);
            this.btnClose.TabIndex = 2;
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose.TextMarginLeft = 0;
            this.btnClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose.UseDefaultRadiusAndThickness = true;
            this.btnClose.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // frmAddEditUser
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(49)))), ((int)(((byte)(60)))));
            this.ClientSize = new System.Drawing.Size(804, 410);
            this.Controls.Add(this.tableLayoutPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmAddEditUser";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "frmAddEditProjet";
            this.Load += new System.EventHandler(this.frmAddEditUser_Load);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            this.tableLayoutPanel3.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        public Bunifu.UI.WinForms.BunifuTextBox textMatrcile;
        public Bunifu.UI.WinForms.BunifuTextBox txtNom;
        public Bunifu.UI.WinForms.BunifuTextBox textPrenom;
        public Bunifu.UI.WinForms.BunifuTextBox textEmail;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuDropdown RoleEmploye;
        public Bunifu.UI.WinForms.BunifuTextBox textPassword;
        public Bunifu.UI.WinForms.BunifuTextBox textAdress;
        public Bunifu.UI.WinForms.BunifuTextBox textTelephone;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private Bunifu.UI.WinForms.BunifuLabel NomLabel;
        public Bunifu.UI.WinForms.BunifuTextBox txtNomContact;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClose;
    }
}